### ISSUE TITLE
Prediction works for direct_nlp but crashes for hybrid and None/default

### ISSUE THREAD

**Issue by howff** [CogStack/nlp2phenome#15]
With `predict_mode` set to `hybrid`
```
[predict_helper.py:26] root 2022-01-17 16:18:18,330 working on [atrophy]
Traceback (most recent call last):
  File "nlp2phenome/predict_helper.py", line 184, in <module>
    predict_to_eHOST_results(sys.argv[1])
  File "nlp2phenome/predict_helper.py", line 165, in predict_to_eHOST_results
    predicted_results = hybrid_prediciton(ss.settings)
  File "nlp2phenome/predict_helper.py", line 78, in hybrid_prediciton
    d2p, labels2work = predict(settings)
  File "nlp2phenome/predict_helper.py", line 43, in predict
    full_text_dir=test_text_dir)
TypeError: load_data_for_predict() got an unexpected keyword argument 'concept_mapping_file'
```

Without `predict_mode`
```
[predict_helper.py:167] root 2022-01-17 16:18:45,485 predicting...
[predict_helper.py:26] root 2022-01-17 16:18:45,486 working on [atrophy]
Traceback (most recent call last):
  File "nlp2phenome/predict_helper.py", line 184, in <module>
    predict_to_eHOST_results(sys.argv[1])
  File "nlp2phenome/predict_helper.py", line 168, in predict_to_eHOST_results
    predicted_results = predict(ss.settings)
  File "nlp2phenome/predict_helper.py", line 43, in predict
    full_text_dir=test_text_dir)
TypeError: load_data_for_predict() got an unexpected keyword argument 'concept_mapping_file'
```

**Comment by Honghan** [comment]
Just updated the predict_helper to fix the issue. This was caused by a code cleaning done back in 2020.

**Comment by howff** [comment]
After applying abff6060cf013531693ce9f4bb98c87edce69993
Now it gives a different error
```
    lm.concept_mapping = _cm_obj
AttributeError: can't set attribute
```

**Comment by howff** [comment]
We can solve that error if we change `lm.concept_mapping = _cm_obj` into `lm._concept_mapping = _cm_obj`

However then we get another error (in None/default mode)
```
in output_eHOST_format
    xml = AnnConverter.to_eHOST(d, doc2precited[d])
TypeError: tuple indices must be integers or slices, not dict
```

**Comment by Honghan** [comment]
No - it's my bad - forgot to push another file `LabelModel.py` which I had added a function to allow attribute setting.
